config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :places
  root to: 'places#index'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'new_account' },
             controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :employees
  validates :name, presence: true
  validates :ext_num, numericality: { only_integer: true }
  validates :int_num, numericality: { only_integer: true }
  validates :pc, numericality: { only_integer: true }, length: { minimum: 5, maximum: 5 }
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[show edit update destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @employees = @place.employees
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit; end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def place_params
    params.require(:place).permit(:name, :street, :suburb, :ext_num, :int_num, :pc, :city, :country)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
  def render_places
    if @places.count.positive?
      render 'places/places'
    else
      render html: '<p>No hay sucursales registradas<p/>'.html_safe
    end
  end
end

app/views/places/_form.html.erb
<div class="card col-lg-6 mr-auto ml-auto p-lg-4">
  <%= form_with(model: place, local: true) do |form| %>
    <% if place.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <ul>
          <% place.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :name, "Nombre de la sucursal" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :street, "Calle" %>
      <%= form.text_field :street, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :suburb, "Colonia" %>
      <%= form.text_field :suburb, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :ext_num, "Numero exterior" %>
      <%= form.number_field :ext_num, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :int_num, "Numero interior" %>
      <%= form.number_field :int_num, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :pc, "Codigo Postal" %>
      <%= form.number_field :pc, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :city, "Ciudad" %>
      <%= form.text_field :city, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :country, "Pais" %>
      <%= form.text_field :country, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar", class: "btn btn-success btn-block" %>
    </div>
  <% end %>
</div>

app/views/places/_places.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Calle</th>
    <th>Colonia</th>
    <th>Num Ext</th>
    <th>Num Int</th>
    <th>Codigo Postal</th>
    <th>Ciudad</th>
    <th>Pais</th>
    <th>Empleados</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @places.each do |place| %>
    <tr>
      <td><%= place.name %></td>
      <td><%= place.street %></td>
      <td><%= place.suburb %></td>
      <td><%= place.ext_num %></td>
      <td><%= place.int_num %></td>
      <td><%= place.pc %></td>
      <td><%= place.city %></td>
      <td><%= place.country %></td>
      <td><%= place.employees.count %></td>
      <td><%= link_to 'Show', place %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', @place %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sucursales</h1>

<div class="mb-lg-3">
  <%= link_to 'Registrar Sucursal', new_place_path, class: "btn btn-success" %>
  <%= link_to_if @places.count.positive?, 'Registrar Empleado', new_employee_path, class: "btn btn-primary" %>
</div>

<%= render_places %>
<br>

app/views/places/new.html.erb
<h1 class="text-center mt-lg-4">Registrar Sucursal</h1>

<div class="container mt-lg-2">
  <%= render 'form', place: @place %>

  <div class="col-lg-6 ml-auto mr-auto mt-lg-3">
    <%= link_to 'Back', places_path %>
  </div>
</div>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sucursal:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @place.street %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @place.suburb %>
</p>

<p>
  <strong>Numero Ext:</strong>
  <%= @place.ext_num %>
</p>

<p>
  <strong>Numero Int:</strong>
  <%= @place.int_num %>
</p>

<p>
  <strong>Codigo Postal:</strong>
  <%= @place.pc %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @place.city %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @place.country %>
</p>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

<%= render 'employees/employees' %>